export const levels = [
  {
    source: { x: 0, y: 5, dir: "right" },
    target: { x: 7, y: 1 },
    obstacles: [
      { x: 4, y: 5 },
      { x: 3, y: 2 },
      { x: 6, y: 8 },
      { x: 3, y: 9 },
    ],
    mirrors: [
      { x: 2, y: 4, angle: 45 },
      { x: 5, y: 1, angle: 135 },
      { x: 6, y: 6, angle: 90 },
    ],
  },
  {
    source: { x: 0, y: 9, dir: "right" },
    target: { x: 5, y: 1 },
    obstacles: [
      { x: 1, y: 0 },
      { x: 2, y: 0 },
      { x: 3, y: 6 },
      { x: 4, y: 4 },
      { x: 5, y: 2 },
      { x: 1, y: 8 },
      { x: 2, y: 8 },
      { x: 4, y: 5 },
      { x: 3, y: 1 },
      { x: 7, y: 8 },
      { x: 6, y: 5 },
    ],
    mirrors: [
      { x: 1, y: 6, angle: 45 },
      { x: 4, y: 6, angle: 135 },
      { x: 1, y: 3, angle: 45 },
      { x: 6, y: 11, angle: 90 },
    ],
  },
  {
    source: { x: 0, y: 11, dir: "right" },
    target: { x: 7, y: 0 },
    obstacles: [
      { x: 1, y: 0 },
      { x: 2, y: 0 },
      { x: 2, y: 7 },
      { x: 3, y: 5 },
      { x: 5, y: 3 },
      { x: 6, y: 1 },

      { x: 0, y: 9 },
      { x: 1, y: 9 },
      { x: 2, y: 9 },
      { x: 3, y: 9 },
      { x: 4, y: 9 },
      { x: 6, y: 9 },
      { x: 7, y: 9 },

      { x: 1, y: 4 },
      { x: 2, y: 4 },
      { x: 3, y: 4 },
      { x: 4, y: 4 },
      { x: 5, y: 4 },
      { x: 7, y: 4 },
    ],
    mirrors: [
      { x: 1, y: 6, angle: 45 },
      { x: 4, y: 7, angle: 135 },
      { x: 2, y: 2, angle: 45 },
      { x: 6, y: 5, angle: 135 },
      { x: 1, y: 2, angle: 45 },
      { x: 5, y: 7, angle: 90 },
    ],
  },
];
